spring:
 profiles:
  active:
   - dev

---
spring:
 profile: dev	#开发环境
 application:
  name: SpringCloud-ConfigServer-dev

---
spring:
 profile: test	#测试环境
 application:
  name: SpringCloud-ConfigServer-test